# App name
spring:
  application:
    name: apigateway
  # Cloud Config
  cloud:
    config:
      uri: http://localhost:8888/
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
            - "http://localhost:4200"
            allowCredentials: true
            allowedMethods:
              - GET
              - POST
              - DELETE
              - PUT
            allowedHeaders: "*"
  config:
    import: configserver:http://localhost:8888/